package com.sample;
 
import com.sample.DroolsTest.Message; 
import java.util.List;
import java.util.HashMap;

global java.util.List list
 
rule "Hello Cruel World 01 "
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Preparing to say goodbye" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye Cruel"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
        System.out.println( " Triggering another rule" );
end


rule "Found goodbye message"
    when
        m :  Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
        System.out.println( " Triggering another rule" );
        m.setStatus(Message.GOODNIGHT);
        m.setMessage("Hold on brother\n");
        update(m)
end

rule "Update message to good nb="
    when
       m : Message( status == Message.GOODNIGHT, myMessage : message )
    then
        System.out.println( myMessage );
        list.add(m);
end

rule "Check if object is Chinese"
    when
       m : HashMap(hometown=="China")
    then
        System.out.println( "Find a Chinese" );
        list.add(m);
end

rule "Check if object konw C++"
    when
       m : HashMap( get("skill") == "C++" )
    then
        System.out.println( "Find a man know C++" );
        m.put("skill","js");
        update(m);
end

rule "Check if object konw js"
    when
       m : HashMap( get("skill") == "js" )
    then
        System.out.println( "Find a man know js" );
        m.put("skill","C++");
end



